### ISSUE TITLE
[stubhub-ticketing] auth service:  kubernet  Deployment , Service

### ISSUE THREAD

**Issue by wakidurrahman** [wakidurrahman/microservices-with-nodes-and-react#28]
# stubhub-ticketing/infra/k8s/auth-deploy.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deploy
spec:
  replicas: 1
  ...
---
apiVersion: v1
kind: Service
metadata:
  name: auth-clusterip-service
spec:
  selector:
    app: auth
    ...
```
