### ISSUE TITLE
[stubhub-ticketing] auth service: Ingress

### ISSUE THREAD

**Issue by wakidurrahman** [wakidurrahman/microservices-with-nodes-and-react#31]
# Ingress

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: stubhub-ticketing.dev
  ...
```
