### ISSUE TITLE
[Docker and Kubernetes] : Docker Compose

### ISSUE THREAD

**Issue by wakidurrahman** [wakidurrahman/microservices-with-nodes-and-react#59]
`compose.yml`
```
version: '3'
services:
  redis-server:
    image: 'redis:alpine'
  node-app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
```

### few initial commands. 
```
$ docker compose up
$ docker compose up --build
$ docker compose up -d 
$ docker compose down
$ docker compose ps
```
